services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'meditactive'
      MYSQL_PASSWORD: 'meditactiveStart2Impact'
      MYSQL_DATABASE: 'meditactive'
    ports:
      - 3306:3306
    expose:
        - 3306
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysqldata:
